elasticsearch:
  build: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - /var/opt/risno/elastic-storage/log/:/var/log/elasticsearch
    - /var/opt/risno/elastic-storage/data/:/var/lib/elasticsearch

node:
  build: nodejs
  volumes:
    - /opt/risno/:/opt/risno
  ports:
    - "12043:12043"
  links:
    - elasticsearch
  env_file: .env

#
# Monitoring
#

cadvisor:
  image: google/cadvisor:0.14.0
  volumes:
   - /:/rootfs:ro
   - /var/run:/var/run:rw
   - /sys:/sys:ro
   - /var/lib/docker/:/var/lib/docker:ro
  ports:
   - "9999:8080"