- name: stockage persistant des journaux
  ini_file: dest=/etc/systemd/journald.conf section=Journal option=Storage value=persistent
  notify: restart systemd-journald.service

- name: add ansible dependencies...
  apt: pkg={{item}}
  with_items:
  - python-apt
  - python-pycurl

- name: install sysstat
  apt: pkg=sysstat
- name: enable sysstat
  lineinfile: dest=/etc/default/sysstat regexp=^ENABLED= line=ENABLED='"true"'

- name: install git
  apt: pkg=git
- name: add github.com to known hosts
  sshknownhosts: host=github.com
- name: ensure risno git repo present
  git: repo=https://github.com/pgrange/risno.git dest=/opt/risno update=yes force=no
