- name: add ansible dependencies...
  apt: pkg={{item}}
  with_items:
  - python-apt
  - python-pycurl

- name: install sysstat
  apt: pkg=sysstat
- name: enable sysstat
  lineinfile: dest=/etc/default/sysstat regexp=^ENABLED= line=ENABLED='"true"'

- name: install git
  apt: pkg=git
- name: add github.com to known hosts
  sshknownhosts: host=github.com
- name: ensure risno git repo present
  git: repo=https://github.com/pgrange/risno.git dest=/opt/risno update=yes force=no

- name: depose docker repo key
  copy: src=docker-repo-key.asc dest=/root/docker-repo-key.asc
- name: add docker repo key
  apt_key: file=/root/docker-repo-key.asc state=present
- name: add docker repo
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main'
- name: install docker
  apt: pkg=lxc-docker

- name: install docker-py with pip
  pip: name=docker-py
 

