- name: start risno web application
  docker:
    name: risno_web
    image: pgrange/risno-web
    state: reloaded
    restart_policy: always
    net: bridge
    links:
      - risno_elasticsearch
    ports:
      - 12043:12043
    env:
      listen_port: 12043
      elastic_db: risno_elasticsearch:9200
      smtp_host: "{{smtp_host}}"
      smtp_user: "{{smtp_user}}"
      smtp_pass: "{{smtp_pass}}"
