---
- name: ensure apt https transport
  apt: pkg=apt-transport-https
- name: depose node repo key
  copy: src=nodesource.gpg.key dest=/root/nodesource.gpg.key
- name: add node repo key
  apt_key: file=/root/nodesource.gpg.key state=present
- name: add node repo
  apt_repository: repo='deb https://deb.nodesource.com/node_0.12 wheezy main'

- name: install risno configuration files
  template: src={{item}} dest=/etc/opt/{{item}}
  with_items:
  - risno.json

- name: install nodejs
  apt: pkg=nodejs

- name: install pip
  apt: pkg=python-pip
- name: install python dependencies with pip
  pip: name={{item.pkg}} version={{item.version}}
  with_items:
  - {pkg: argparse, version: 1.2.1}
  - {pkg: beautifulsoup4, version: 4.3.2}
  - {pkg: colorama, version: 0.2.7}
  - {pkg: pyes, version: 0.90.1}
  - {pkg: six, version: 1.5.2}
  - {pkg: urllib3, version: 1.7.1}
  - {pkg: wsgiref, version: 0.1.2}
 
- name: create risno user to run crons
  user: name=risno
        shell=/bin/false createhome=no
- name: crontab to fetch new pubs
  cron: name="fetch pubs from sites" cron_file=risno user=risno
        hour=11 minute=1
        job="node /opt/risno/slurp/fetch_sites >>/var/opt/risno/fetch.log 2>&1"
- name: remove old crontab to fetch new pubs
  cron: name="fetch pubs" cron_file=risno user=risno
        hour=15 minute=1
        job="python /opt/risno/fetch_pubs.py --logic-immo --se-loger --paru-vendu --avendre-alouer --pages-jaunes --immo-street --belle-immobilier --region aquitaine >>/var/opt/risno/risno.log 2>&1"
        state="absent"
- name: crontab to update locations
  cron: name="update locations" cron_file=risno user=risno
        hour=17 minute=10
        job="python /opt/risno/update_locations.py >>/var/opt/risno/upd_locations.log 2>&1" 
- name: crontab to update types
  cron: name="update types" cron_file=risno user=risno
        hour=17 minute=1
        job="python /opt/risno/update_type.py >>/var/opt/risno/upd_types.log 2>&1" 
- name: crontab to check for expired pubs
  cron: name="expire pubs" cron_file=risno user=risno
        hour=1 minute=1
        job="python /opt/risno/expire_pubs.py --logic-immo --se-loger --paru-vendu --avendre-alouer --pages-jaunes --immo-street --belle-immobilier --le-bon-coin --annonces-jaunes >>/var/opt/risno/expire.log 2>&1"
- name: crontab to purge expired pubs
  cron: name="purge expired pubs" cron_file=risno user=risno
        hour=2 minute=1
        job="python /opt/risno/purge_pubs.py >>/var/opt/risno/purge.log 2>&1"
