#TODO remove when slurp package correctly
- name: ensure apt https transport
  apt: pkg=apt-transport-https
- name: depose node repo key
  copy: src=nodesource.gpg.key dest=/root/nodesource.gpg.key
- name: add node repo key
  apt_key: file=/root/nodesource.gpg.key state=present
- name: add node repo
  apt_repository: repo='deb https://deb.nodesource.com/node_0.12 wheezy main'

- name: install nodejs
  apt: pkg=nodejs

- name: install pip
  apt: pkg=python-pip
- name: install python dependencies with pip
  pip: name={{item.pkg}} version={{item.version}}
  with_items:
  - {pkg: argparse, version: 1.2.1}
  - {pkg: beautifulsoup4, version: 4.3.2}
  - {pkg: colorama, version: 0.2.7}
  - {pkg: pyes, version: 0.90.1}
  - {pkg: six, version: 1.5.2}
  - {pkg: urllib3, version: 1.7.1}
  - {pkg: wsgiref, version: 0.1.2}
 
- name: create risno user to run crons
  user: name=risno
        shell=/bin/false createhome=no
- name: crontab to fetch new pubs for Aquitaine
  cron: name="fetch pubs from sites for aquitaine" cron_file=risno user=risno
        hour=11 minute=1
        job="node /opt/risno/slurp/fetch_sites aquitaine >>/var/opt/risno/fetch_aquitaine.log 2>&1"
- name: crontab to fetch new pubs for Midi-Pyrenees
  cron: name="fetch pubs from sites for midi_pyrenees" cron_file=risno user=risno
        hour=9 minute=1
        job="node /opt/risno/slurp/fetch_sites midi_pyrenees >>/var/opt/risno/fetch_midi_pyrenees.log 2>&1"
- name: crontab to update locations
  cron: name="update locations" cron_file=risno user=risno
        hour=17 minute=1
        job="python /opt/risno/tools/update_locations.py >>/var/opt/risno/upd_locations.log 2>&1" 
- name: crontab to update types
  cron: name="update types" cron_file=risno user=risno
        hour=15 minute=1
        job="python /opt/risno/tools/update_type.py >>/var/opt/risno/upd_types.log 2>&1" 
- name: install moreutils for ts in following cron
  apt: pkg=moreutils
- name: crontab to check for expired pubs
  cron: name="expire pubs" cron_file=risno user=risno
        hour="14,16,18,23" minute=35
        job="/opt/risno/tools/expire_pubs.sh 2>&1 | ts >>/var/opt/risno/expire.log 2>&1"
- name: crontab to purge expired pubs
  cron: name="purge expired pubs" cron_file=risno user=risno
        hour=2 minute=1
        job="python /opt/risno/tools/purge_pubs.py >>/var/opt/risno/purge.log 2>&1"

- name: install logrotate
  apt: pkg=logrotate

- name: setup risno/slurp logrotate policy
  copy: src=slurp dest=/etc/logrotate.d
